### ISSUE TITLE
Blank Welcome to SWAG Screen

### ISSUE THREAD

**Issue by NathanielH-snek** [marcwagner/foundry_swag_docker#2]
Not sure what I'm doing incorrectly but I'm not getting the foundry login in screen. I only seem to get this 
![Screenshot 2024-06-15 at 6 51 05 PM](https://github.com/ChefsSlaad/foundry_swag_docker/assets/108092467/47165881-66d3-48ad-80c2-eb45cfa25c90)
I'm genuinely not sure what I'm doing incorretly as the containers and associated processes seem to be working fine. Here's my config file for the containers.
```
version: "3.8"

services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York                                     # replace with your local timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - SUBDOMAINS=notroll20                                   # replace with to your DuckDNS subdomain name.
      - TOKEN=<my_token>                                    # replace with your DuckDNS token here
    restart: unless-stopped

  foundry:
    container_name: foundry
    hostname: foundry
    image: direckthit/fvtt-docker:latest
    expose:
      - 30000
    volumes:
      - ~/foundry/data:/data/foundryvtt     # replace with the correct path to your foundry config dir
      - ~/foundry/resources:/data/foundryvtt/Data/resources  # replace with the correct path to your resources
      - ~/foundry/zip:/host                     # replace with the correct path to your foundry-x.x.x.zip file
    restart: unless-stopped

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York                                     # replace with your timezone
      - URL=notroll20.duckdns.org                               # replace with this to your DuckDNS hostname
      - VALIDATION=http
      - DUCKDNSTOKEN=<my_token>                             # replace with your DuckDNS token here
      - EMAIL=<my_email>                              # replace with your email address (optional).
    volumes:
      - ./swag:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
```
